//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sale
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleSagaDataDb
    {
        public System.Guid SaleId { get; set; }
        public string Products { get; set; }
    }
}
