//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sale
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IceCreamShop_SaleEntities : DbContext
    {
        public IceCreamShop_SaleEntities()
            : base("name=IceCreamShop_SaleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<SalePosition> SalePositions { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<SemiFinishedGood> SemiFinishedGoods { get; set; }
        public virtual DbSet<SaleSagaDataDb> SaleSagaDataDbs { get; set; }
    }
}
